name: Nightly CI
on:
  push:
    branches:
      - master
      - main
      - /^release-.*$/
    paths:
      - '.github/workflows/CI.yml'
      - 'test/**'
      - 'src/**'
      - 'deps/**'
      - 'Project.toml'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - '.github/workflows/CI.yml'
      - 'test/**'
      - 'src/**'
      - 'deps/**'
      - 'Project.toml'
jobs:
  test:
    name: Julia Nightly - ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: julia-actions/setup-julia@v1
        with:
          version: 'nightly'
      - uses: actions/cache@v2
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-artifacts-${{ hashFiles('**/Project.toml') }}
          restore-keys: ${{ runner.os }}-test-artifacts
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: lcov.info
